### ISSUE TITLE
Not sure if this is a Bug, or problem with my Text Editor (VS Codium)

### ISSUE THREAD

**Issue by randrums** [wjh18/hugo-liftoff#24]
**Describe the bug**
I'm trying to comment out a line for **series** in my hugo.toml file, per the hugo-liftoff Wiki section, "Taxonomies". Here is the link to that particular paragraph: https://github.com/wjh18/hugo-liftoff/wiki/3.-Config-&-Params#taxonomies

In the hugo.toml file, I've tried putting a # (just one on the entire beginning of the line) and save it. But the Hugo Server gives errors until I remove the comment. This is the section I'm referring to: Please disregard the spacing, as it pasted strange here in the box I'm typing this in:
---
[taxonomies]
    tag = 'tags'
    category = 'categories'    
#  series = 'series' # Allows you to create an organized series of posts (e.g. multi-part tutorial)
    project-type = 'project types' # Categorize projects by type (e.g. client work, personal, open source, etc.)
---
**Expected behavior**
I expected the Series option to go away from posts that have it included.
**Screenshots**
![image](https://github.com/wjh18/hugo-liftoff/assets/73252280/cfa3b63b-5219-4e93-afd0-0bcd5602d83d)

**Desktop (please complete the following information):**
Windows 11
Edge Version 114.0.1823.82 (Official build) (64-bit)
No Add-ins or extensions installed
**Smartphone (please complete the following information):**
Not using smartphone for this site, but I do have a Galaxy s23 Ultra

**Additional context**
Problem goes away if I remove the comment and allow the **series** to exist.

I'd like to add that I believe this is the best Hugo Theme I've ever seen and It needs more recognition than the other "best themes" out there. This one is superior, in my opinion.

**Comment by wjh18** [comment]
Yes, I see the issue. Two example site posts (what you copied over from `themes/hugo-liftoff/exampleSite` into your own project) have a `series` frontmatter param and the open graph `see_more` tag is still trying to index any post with a series param even if the series taxonomy is disabled in the config. I will add an additional check to determine if the taxonomy exists before trying to add the OG tag for posts with series frontmatter.

In the meantime, to get the error to go away you can remove that `series` param from your project's `content/posts/subsection2/*` (should be two posts causing the issue).

Thanks for bringing this to my attention! Will fix in the next release and add clarification to the docs.

> I'd like to add that I believe this is the best Hugo Theme I've ever seen and It needs more recognition than the other "best themes" out there. This one is superior, in my opinion.

Thank you so much! That's great to hear as I worked really hard on it. I only recently added it to the showcase which is why it's not as popular. Slowly gaining traction though, so fingers crossed. If you can find the time to share it on socials or anywhere else that would be a huge help.

**Comment by randrums** [comment]
You're the best, thank you so much!
